=== petegee/AHPerformanceComparison/PerformanceComparison/schemas/aircraft.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by Chris (private) -->
<!--W3C Schema generated by XMLSPY v5 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="aircraft">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="details" />
        <xs:element ref="performance" />
      </xs:sequence>
    </xs:complexType>
    <xs:key name="aircraftKey1">
      <xs:selector xpath="." />
      <xs:field xpath="details/type" />
    </xs:key>
  </xs:element>
  <xs:element name="altitude">
    <xs:simpleType>
      <xs:restriction base="xs:short" />
    </xs:simpleType>
  </xs:element>
  <xs:element name="climb">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cmeasure" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="wep" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="off" />
            <xs:enumeration value="on" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="altUnit" type="xs:string" use="required" />
      <xs:attribute name="rateUnit" type="xs:string" use="required" />
      <xs:attribute name="altFactor" type="xs:float" use="optional" default="1.0" />
      <xs:attribute name="rateFactor" type="xs:float" use="optional" default="1.0" />
      <xs:attribute name="altOffset" type="xs:short" use="optional" default="0" />
      <xs:attribute name="rateOffset" type="xs:short" use="optional" default="0" />
    </xs:complexType>
  </xs:element>
  <xs:element name="details">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="type" />
        <xs:element ref="fuel" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fuel">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:byte">
          <xs:attribute name="unit" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="smeasure">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="altitude" />
        <xs:element ref="tas" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="performance">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="speed" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="climb" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="turn" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="turnData" />
              <xs:element ref="turnData" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rate">
    <xs:simpleType>
      <xs:restriction base="xs:short" />
    </xs:simpleType>
  </xs:element>
  <xs:element name="speed">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="smeasure" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="wep" type="xs:string" use="required" />
      <xs:attribute name="altUnit" type="xs:string" use="required" />
      <xs:attribute name="tasUnit" type="xs:string" use="required" />
      <xs:attribute name="altFactor" type="xs:float" use="optional" default="1.0" />
      <xs:attribute name="tasFactor" type="xs:float" use="optional" default="1.0" />
      <xs:attribute name="altOffset" type="xs:short" use="optional" default="0" />
      <xs:attribute name="tasOffset" type="xs:short" use="optional" default="0" />
    </xs:complexType>
  </xs:element>
  <xs:element name="tas">
    <xs:simpleType>
      <xs:restriction base="xs:short" />
    </xs:simpleType>
  </xs:element>
  <xs:element name="type" type="xs:string" />
  <xs:element name="cmeasure">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="altitude" />
        <xs:element ref="rate" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="turnData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sustainedTurnRadius" type="xs:float" />
        <xs:element name="sustainedTurnRate" type="xs:float" />
        <xs:element name="speed" type="xs:float" />
        <xs:element name="time" type="xs:float" />
        <xs:element name="stallSpeed" type="xs:float" />
        <xs:element name="cornerVelocity" type="xs:float" />
        <xs:element name="turnRateAtCorner" type="xs:float" />
        <xs:element name="turnRadiusAtCorner" type="xs:float" />
      </xs:sequence>
      <xs:attribute name="flapPosition" type="xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== petegee/AHPerformanceComparison/PerformanceComparison/airData/P-38L.xml
<?xml version="1.0" encoding="UTF-8"?><aircraft xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\ChrisWork\sourceRoot\Project\Other\PerformanceComparison\schemas\aircraft.xsd"><details><type>P-38L</type><fuel unit="gallon">0</fuel></details><performance><speed wep="off" altUnit="feet" tasUnit="mph"><smeasure><altitude>0</altitude><tas>339</tas></smeasure><smeasure><altitude>25111</altitude><tas>401</tas></smeasure><smeasure><altitude>28555</altitude><tas>398</tas></smeasure><smeasure><altitude>30000</altitude><tas>395</tas></smeasure></speed><speed wep="on" altUnit="feet" tasUnit="mph"><smeasure><altitude>0</altitude><tas>344</tas></smeasure><smeasure><altitude>2333</altitude><tas>350</tas></smeasure><smeasure><altitude>4111</altitude><tas>357</tas></smeasure><smeasure><altitude>5222</altitude><tas>358</tas></smeasure><smeasure><altitude>6556</altitude><tas>364</tas></smeasure><smeasure><altitude>8444</altitude><tas>368</tas></smeasure><smeasure><altitude>9778</altitude><tas>374</tas></smeasure><smeasure><altitude>12889</altitude><tas>381</tas></smeasure><smeasure><altitude>14000</altitude><tas>383</tas></smeasure><smeasure><altitude>15000</altitude><tas>388</tas></smeasure><smeasure><altitude>20000</altitude><tas>403</tas></smeasure><smeasure><altitude>21110</altitude><tas>405</tas></smeasure><smeasure><altitude>24478</altitude><tas>416</tas></smeasure><smeasure><altitude>26222</altitude><tas>417</tas></smeasure><smeasure><altitude>28222</altitude><tas>411</tas></smeasure><smeasure><altitude>30000</altitude><tas>403</tas></smeasure></speed><climb wep="off" altUnit="feet" rateUnit="fpm"><cmeasure><altitude>0</altitude><rate>3204</rate></cmeasure><cmeasure><altitude>3778</altitude><rate>3170</rate></cmeasure><cmeasure><altitude>8222</altitude><rate>3118</rate></cmeasure><cmeasure><altitude>11000</altitude><rate>3034</rate></cmeasure><cmeasure><altitude>16000</altitude><rate>2797</rate></cmeasure><cmeasure><altitude>21555</altitude><rate>2526</rate></cmeasure><cmeasure><altitude>26000</altitude><rate>2221</rate></cmeasure><cmeasure><altitude>30000</altitude><rate>1678</rate></cmeasure></climb><climb wep="on" altUnit="feet" rateUnit="fpm"><cmeasure><altitude>0</altitude><rate>3746</rate></cmeasure><cmeasure><altitude>3667</altitude><rate>3695</rate></cmeasure><cmeasure><altitude>6444</altitude><rate>3644</rate></cmeasure><cmeasure><altitude>10111</altitude><rate>3509</rate></cmeasure><cmeasure><altitude>16889</altitude><rate>3102</rate></cmeasure><cmeasure><altitude>19555</altitude><rate>2932</rate></cmeasure><cmeasure><altitude>21555</altitude><rate>2729</rate></cmeasure><cmeasure><altitude>26000</altitude><rate>2221</rate></cmeasure><cmeasure><altitude>30000</altitude><rate>1678</rate></cmeasure></climb><turn><turnData flapPosition="none"><speed>185.00</speed><time>19.00</time><sustainedTurnRate>18.9</sustainedTurnRate><sustainedTurnRadius>820</sustainedTurnRadius><stallSpeed>107</stallSpeed><cornerVelocity>263</cornerVelocity><turnRateAtCorner>28.2</turnRateAtCorner><turnRadiusAtCorner>783</turnRadiusAtCorner></turnData><turnData flapPosition="full"><speed>144.00</speed><time>17.8</time><sustainedTurnRate>20.2</sustainedTurnRate><sustainedTurnRadius>598</sustainedTurnRadius><stallSpeed>91</stallSpeed><cornerVelocity>222</cornerVelocity><turnRateAtCorner>33.5</turnRateAtCorner><turnRadiusAtCorner>557</turnRadiusAtCorner></turnData></turn></performance></aircraft>

=== petegee/AHPerformanceComparison/PerformanceComparison/airData.original/P-51B.xml
<?xml version="1.0" encoding="UTF-8"?>
<aircraft xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\ChrisWork\sourceRoot\Project\Other\PerformanceComparison\schemas\aircraft.xsd">
	<details>
		<type>P51-B</type>
		<fuel unit="gallon">0</fuel>
	</details>
	<performance>
		<speed wep="off" altUnit="feet" tasUnit="mph">
			<smeasure>
				<altitude>0</altitude>
				<tas>349</tas>
			</smeasure>
			<smeasure>
				<altitude>1556</altitude>
				<tas>354</tas>
			</smeasure>
			<smeasure>
				<altitude>17111</altitude>
				<tas>424</tas>
			</smeasure>
			<smeasure>
				<altitude>23778</altitude>
				<tas>411</tas>
			</smeasure>
			<smeasure>
				<altitude>30000</altitude>
				<tas>439</tas>
			</smeasure>
		</speed>
		<speed wep="on" altUnit="feet" tasUnit="mph">
			<smeasure>
				<altitude>0</altitude>
				<tas>360</tas>
			</smeasure>
			<smeasure>
				<altitude>16111</altitude>
				<tas>425</tas>
			</smeasure>
			<smeasure>
				<altitude>21889</altitude>
				<tas>415</tas>
			</smeasure>
			<smeasure>
				<altitude>22889</altitude>
				<tas>418</tas>
			</smeasure>
			<smeasure>
				<altitude>25778</altitude>
				<tas>430</tas>
			</smeasure>
			<smeasure>
				<altitude>28889</altitude>
				<tas>445</tas>
			</smeasure>
			<smeasure>
				<altitude>30000</altitude>
				<tas>442</tas>
			</smeasure>
		</speed>
		<climb wep="off" altUnit="feet" rateUnit="fpm">
			<cmeasure>
				<altitude>0</altitude>
				<rate>2900</rate>
			</cmeasure>
			<cmeasure>
				<altitude>15780</altitude>
				<rate>3185</rate>
			</cmeasure>
			<cmeasure>
				<altitude>21780</altitude>
				<rate>2539</rate>
			</cmeasure>
			<cmeasure>
				<altitude>26670</altitude>
				<rate>2422</rate>
			</cmeasure>
			<cmeasure>
				<altitude>27780</altitude>
				<rate>2422</rate>
			</cmeasure>
			<cmeasure>
				<altitude>30000</altitude>
				<rate>2030</rate>
			</cmeasure>
		</climb>
		<climb wep="on" altUnit="feet" rateUnit="fpm">
			<cmeasure>
				<altitude>0</altitude>
				<rate>3175</rate>
			</cmeasure>
			<cmeasure>
				<altitude>14222</altitude>
				<rate>3408</rate>
			</cmeasure>
			<cmeasure>
				<altitude>18889</altitude>
				<rate>2857</rate>
			</cmeasure>
			<cmeasure>
				<altitude>26222</altitude>
				<rate>2708</rate>
			</cmeasure>
			<cmeasure>
				<altitude>30000</altitude>
				<rate>2030</rate>
			</cmeasure>
		</climb>
    <turn>
      <turnData flapPosition="none">
        <radius>233.42</radius>
        <degPerSec>17.70</degPerSec>
        <speed>162.00</speed>
        <time>21.33</time>
      </turnData>
      <turnData flapPosition="full">
        <radius>182.21</radius>
        <degPerSec>16.20</degPerSec>
        <speed>116.00</speed>
        <time>22.16</time>
      </turnData>
    </turn>
	</performance>
</aircraft>
